# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TVSTcJgxT3kR1_2dQO-ivNUsq0bRAU-p
"""

# student_ops_cli.py

import csv
import os

FILENAME = "students.csv"

def add_student():
    file_exists = os.path.isfile(FILENAME)

    name = input("Enter student name: ")
    attendance = int(input("Enter attendance (%): "))
    marks = int(input("Enter marks: "))

    with open(FILENAME, "a", newline="") as file:
        writer = csv.writer(file)
        if not file_exists:
            writer.writerow(["Name", "Attendance", "Marks"])
        writer.writerow([name, attendance, marks)

    print("Student added successfully!")

def view_students():
    if not os.path.exists(FILENAME):
        print("No records found.")
        return

    with open(FILENAME, "r") as file:
        reader = csv.reader(file)
        for row in reader:
            print(row)

def menu():
    while True:
        print("\n1. Add Student")
        print("2. View Students")
        print("3. Exit")

        choice = input("Choose option: ")

        if choice == "1":
            add_student()
        elif choice == "2":
            view_students()
        elif choice == "3":
            break
        else:
            print("Invalid choice")

menu()

